sonar.projectKey=thec1rcle
sonar.organization=thec1rclehost123-cmd

# This is the name and version displayed in the SonarCloud UI.
# sonar.projectName=TheC1rcle
# sonar.projectVersion=1.0

# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
sonar.sources=apps,packages

# Encoding of the source code. Default is default system encoding
sonar.sourceEncoding=UTF-8

# Exclusions
sonar.exclusions=**/node_modules/**, **/.next/**, **/dist/**, **/coverage/**, **/*.test.ts, **/*.test.js, **/scripts/**
