export const guestV1OpenApi = {
    openapi: '3.1.0',
    info: {
        title: 'C1RCLE Guest API',
        version: '1.0.0',
        description: 'Canonical guest-facing Fastify contract consumed by apps/guest-portal.',
    },
    servers: [{ url: '/api/v1' }],
    components: {
        securitySchemes: {
            cookieSession: {
                type: 'apiKey',
                in: 'cookie',
                name: '__session',
            },
        },
        schemas: {
            StandardErrorResponse: {
                type: 'object',
                required: ['error'],
                properties: {
                    error: {
                        type: 'object',
                        required: ['code', 'message'],
                        properties: {
                            code: { type: 'string' },
                            message: { type: 'string' },
                            details: {},
                            requestId: { type: 'string' },
                        },
                    },
                },
            },
        },
    },
    paths: {
        '/auth/me': { get: { operationId: 'getGuestAuthBootstrap', tags: ['auth'] } },
        '/auth/csrf': { get: { operationId: 'getGuestCsrfBootstrap', tags: ['auth'] } },
        '/auth/login': { post: { operationId: 'loginGuest', tags: ['auth'] } },
        '/auth/register': { post: { operationId: 'registerGuest', tags: ['auth'] } },
        '/auth/logout': { post: { operationId: 'logoutGuest', tags: ['auth'] } },
        '/auth/check': { post: { operationId: 'checkGuestEmail', tags: ['auth'] } },
        '/auth/change-password': { post: { operationId: 'changeGuestPassword', tags: ['auth'] } },
        '/auth/password-reset': { post: { operationId: 'requestGuestPasswordReset', tags: ['auth'] } },
        '/auth/otp/send': { post: { operationId: 'sendGuestOtp', tags: ['auth'] } },
        '/auth/otp/verify': { post: { operationId: 'verifyGuestOtp', tags: ['auth'] } },
        '/profiles/personal': { patch: { operationId: 'updateGuestPersonalProfile', tags: ['profiles'] } },
        '/profiles/social': { patch: { operationId: 'updateGuestSocialProfile', tags: ['profiles'] } },
        '/profiles/bio': { patch: { operationId: 'updateGuestBioProfile', tags: ['profiles'] } },
        '/profiles/avatar': { patch: { operationId: 'updateGuestAvatarProfile', tags: ['profiles'] } },
        '/users/profile': { post: { operationId: 'createGuestProfile', tags: ['profiles'] } },
        '/guest-profiles/{id}': { get: { operationId: 'getGuestPublicProfile', tags: ['profiles'] } },
        '/guest-profiles/lookup': { get: { operationId: 'lookupGuestProfile', tags: ['profiles'] } },
        '/guest-profiles/avatar': { post: { operationId: 'uploadGuestAvatar', tags: ['profiles'] } },
        '/public/events': { get: { operationId: 'listPublicEvents', tags: ['discovery'] } },
        '/public/events/featured': { get: { operationId: 'listFeaturedEvents', tags: ['discovery'] } },
        '/public/events/{idOrSlug}': { get: { operationId: 'getPublicEvent', tags: ['discovery'] } },
        '/public/hosts': { get: { operationId: 'listPublicHosts', tags: ['discovery'] } },
        '/public/hosts/{slug}': { get: { operationId: 'getPublicHost', tags: ['discovery'] } },
        '/public/venues': { get: { operationId: 'listPublicVenues', tags: ['discovery'] } },
        '/public/venues/{slug}': { get: { operationId: 'getPublicVenue', tags: ['discovery'] } },
        '/public/search': { get: { operationId: 'searchPublicDiscovery', tags: ['discovery'] } },
        '/public/homepage/selects': { get: { operationId: 'listHomepageSelects', tags: ['discovery'] } },
        '/public/homepage/interviews': { get: { operationId: 'listHomepageInterviews', tags: ['discovery'] } },
        '/public/promoters/{username}': { get: { operationId: 'getPublicPromoter', tags: ['promoters'] } },
        '/public/promoters/{username}/links/{alias}': { get: { operationId: 'resolvePromoterVanityLink', tags: ['promoters'] } },
        '/promoter/links/click': { post: { operationId: 'trackPromoterLinkClick', tags: ['promoters'] } },
        '/checkout/calculate': { post: { operationId: 'calculateCheckout', tags: ['checkout'] } },
        '/checkout/promo': { post: { operationId: 'validateCheckoutPromo', tags: ['checkout'] } },
        '/checkout/reserve': { post: { operationId: 'reserveCheckoutInventory', tags: ['checkout'] } },
        '/checkout/initiate': { post: { operationId: 'initiateCheckout', tags: ['checkout'] } },
        '/payments/config': { get: { operationId: 'getPaymentConfig', tags: ['payments'] } },
        '/payments/order': { post: { operationId: 'createPaymentOrder', tags: ['payments'] } },
        '/payments/verify': { patch: { operationId: 'verifyPayment', tags: ['payments'] } },
        '/orders/{orderId}': { get: { operationId: 'getGuestOrder', tags: ['orders'] } },
        '/orders/{orderId}/cancel': {
            get: { operationId: 'getOrderCancelEligibility', tags: ['orders'] },
            post: { operationId: 'requestOrderCancel', tags: ['orders'] },
        },
        '/tickets': { get: { operationId: 'getGuestTickets', tags: ['tickets'] } },
        '/tickets/share': { post: { operationId: 'createTicketShareBundle', tags: ['tickets'] } },
        '/tickets/claim': { get: { operationId: 'getTicketShareBundle', tags: ['tickets'] } },
        '/tickets/claim/share': { post: { operationId: 'claimSharedTicket', tags: ['tickets'] } },
        '/tickets/pair': { post: { operationId: 'claimPartnerSlot', tags: ['tickets'] } },
        '/tickets/pair/assign': { post: { operationId: 'assignPartnerTicket', tags: ['tickets'] } },
        '/tickets/pair/link': { post: { operationId: 'createPartnerClaimLink', tags: ['tickets'] } },
        '/tickets/pair/transfer': { post: { operationId: 'transferCoupleTicket', tags: ['tickets'] } },
        '/tickets/transfer': {
            post: { operationId: 'initiateTicketTransfer', tags: ['tickets'] },
            patch: { operationId: 'acceptTicketTransfer', tags: ['tickets'] },
            delete: { operationId: 'cancelTicketTransfer', tags: ['tickets'] },
        },
        '/tickets/cover-wallet': { get: { operationId: 'getTicketCoverWallet', tags: ['tickets'] } },
        '/cover-charge/wallet/{walletId}': { get: { operationId: 'getCoverChargeWallet', tags: ['tickets'] } },
        '/events/{eventId}/view': { post: { operationId: 'recordEventView', tags: ['events'] } },
        '/events/{eventId}/track': { post: { operationId: 'trackEventInteraction', tags: ['events'] } },
        '/events/{eventId}/rsvp': { post: { operationId: 'setEventRsvp', tags: ['events'] } },
        '/events/{eventId}/queue': {
            get: { operationId: 'getEventQueue', tags: ['events'] },
            post: { operationId: 'joinEventQueue', tags: ['events'] },
        },
        '/waitlist/join': { post: { operationId: 'joinWaitlist', tags: ['events'] } },
        '/follow': {
            get: { operationId: 'getFollowStatus', tags: ['social'] },
            post: { operationId: 'followEntity', tags: ['social'] },
            delete: { operationId: 'unfollowEntity', tags: ['social'] },
        },
        '/venues/{venueId}/follow-status': { get: { operationId: 'getVenueFollowStatus', tags: ['venues'] } },
        '/venues/{venueId}/follow': {
            post: { operationId: 'followVenue', tags: ['venues'] },
            delete: { operationId: 'unfollowVenue', tags: ['venues'] },
        },
        '/venue-settings/venue/reservations': { post: { operationId: 'createVenueReservation', tags: ['venues'] } },
        '/guest-notifications': {
            get: { operationId: 'listGuestNotifications', tags: ['notifications'] },
            patch: { operationId: 'updateGuestNotifications', tags: ['notifications'] },
        },
        '/guest-notifications/{id}': { patch: { operationId: 'markGuestNotificationRead', tags: ['notifications'] } },
        '/passes/apple': { get: { operationId: 'getAppleWalletPass', tags: ['passes'] } },
        '/passes/google': { get: { operationId: 'getGoogleWalletPass', tags: ['passes'] } },
    },
} as const;

export type GuestV1OpenApi = typeof guestV1OpenApi;
