/**
 * Demo data for all stores.
 * Toggle DEMO_MODE = true to inject this data everywhere in the app.
 * Useful for UI demos and screenshots.
 */

import { DEMO_POSTERS } from "./posters";

export const DEMO_MODE = true;

// ── Events ────────────────────────────────────────────────────────────────────

export const DEMO_EVENTS = [
    {
        id: "demo-event-01",
        title: "Neon District",
        description: "Pune's biggest underground electronic music night. Featuring live sets from Mumbai's top DJs spinning techno, minimal, and dark house all night long.",
        startDate: "2026-04-26T21:00:00.000Z",
        endDate: "2026-04-27T04:00:00.000Z",
        venue: "Ishanya, Pune",
        location: "Ishanya Mall, Pune",
        city: "Pune",
        hostId: "demo-host-01",
        hostName: "Colosseum Pune",
        coverImage: DEMO_POSTERS.neonDistrict,
        poster: DEMO_POSTERS.neonDistrict,
        image: DEMO_POSTERS.neonDistrict,
        lifecycle: "scheduled",
        status: "active",
        isFeatured: true,
        heatScore: 94,
        category: "club",
        tags: ["techno", "electronic", "nightlife", "18+"],
        tickets: [
            { id: "t1", name: "Early Bird", price: 499, quantity: 100, remaining: 23, entryType: "couple" },
            { id: "t2", name: "Regular Entry", price: 799, quantity: 200, remaining: 87 },
            { id: "t3", name: "VIP Table", price: 3999, quantity: 20, remaining: 5, entryType: "table" },
        ],
        stats: { views: 4820, saves: 312, shares: 89, rsvps: 410 },
        coordinates: { latitude: 18.5204, longitude: 73.8567 },
    },
    {
        id: "demo-event-02",
        title: "Aqua Sundays",
        description: "Sunday brunch vibes with live Bollywood DJ sets, unlimited drinks, and a curated gourmet buffet. Dress sharp.",
        startDate: "2026-04-27T11:00:00.000Z",
        endDate: "2026-04-27T16:00:00.000Z",
        venue: "The Bund, Pune",
        location: "The Bund, Kalyani Nagar, Pune",
        city: "Pune",
        hostId: "demo-host-02",
        hostName: "The Bund",
        coverImage: DEMO_POSTERS.aquaSundays,
        poster: DEMO_POSTERS.aquaSundays,
        image: DEMO_POSTERS.aquaSundays,
        lifecycle: "scheduled",
        status: "active",
        isFeatured: true,
        heatScore: 88,
        category: "brunch",
        tags: ["bollywood", "brunch", "unlimited-drinks", "sunday"],
        tickets: [
            { id: "t1", name: "Couple Pass", price: 1499, quantity: 60, remaining: 18 },
            { id: "t2", name: "Stag Entry", price: 999, quantity: 30, remaining: 12 },
        ],
        stats: { views: 3100, saves: 201, shares: 67, rsvps: 220 },
        coordinates: { latitude: 18.5362, longitude: 73.9003 },
    },
    {
        id: "demo-event-03",
        title: "Red Room",
        description: "Mumbai's premier drum & bass and jungle music event is back. Warehouse venue, world-class sound system, two stages.",
        startDate: "2026-05-03T22:00:00.000Z",
        endDate: "2026-05-04T05:00:00.000Z",
        venue: "NSCI Dome, Mumbai",
        location: "NSCI Dome, Worli, Mumbai",
        city: "Mumbai",
        hostId: "demo-host-03",
        hostName: "Bass Station India",
        coverImage: DEMO_POSTERS.redRoom,
        poster: DEMO_POSTERS.redRoom,
        image: DEMO_POSTERS.redRoom,
        lifecycle: "scheduled",
        status: "active",
        isFeatured: true,
        heatScore: 97,
        category: "concert",
        tags: ["dnb", "bass", "warehouse", "two-stages"],
        tickets: [
            { id: "t1", name: "GA", price: 699, quantity: 500, remaining: 142 },
            { id: "t2", name: "VIP", price: 1499, quantity: 80, remaining: 31 },
        ],
        stats: { views: 8900, saves: 621, shares: 210, rsvps: 880 },
        coordinates: { latitude: 19.0176, longitude: 72.8143 },
    },
    {
        id: "demo-event-04",
        title: "Velvet Nights",
        description: "Curated cocktails, live jazz trio, and the best sunset view in Bandra. Limited to 80 guests for an intimate experience.",
        startDate: "2026-04-25T18:30:00.000Z",
        endDate: "2026-04-25T23:00:00.000Z",
        venue: "Howzat Bar & Kitchen, Bandra",
        location: "Howzat, Bandra West, Mumbai",
        city: "Mumbai",
        hostId: "demo-host-04",
        hostName: "Howzat Mumbai",
        coverImage: DEMO_POSTERS.velvetNights,
        poster: DEMO_POSTERS.velvetNights,
        image: DEMO_POSTERS.velvetNights,
        lifecycle: "scheduled",
        status: "active",
        isFeatured: false,
        heatScore: 76,
        category: "party",
        tags: ["rooftop", "jazz", "cocktails", "sunset", "intimate"],
        tickets: [
            { id: "t1", name: "Entry", price: 599, quantity: 80, remaining: 11 },
        ],
        stats: { views: 2400, saves: 188, shares: 42, rsvps: 69 },
        coordinates: { latitude: 19.0596, longitude: 72.8295 },
    },
    {
        id: "demo-event-05",
        title: "Eclipse",
        description: "Psychedelic trance night under the stars on Anjuna beach. International artists, laser light show, and the original Goa spirit.",
        startDate: "2026-05-10T20:00:00.000Z",
        endDate: "2026-05-11T06:00:00.000Z",
        venue: "Anjuna Beach, Goa",
        location: "Anjuna Beach, North Goa",
        city: "Goa",
        hostId: "demo-host-05",
        hostName: "Shiva Valley Goa",
        coverImage: DEMO_POSTERS.eclipse,
        poster: DEMO_POSTERS.eclipse,
        image: DEMO_POSTERS.eclipse,
        lifecycle: "scheduled",
        status: "active",
        isFeatured: true,
        heatScore: 99,
        category: "festival",
        tags: ["psytrance", "beach", "goa", "international", "outdoor"],
        tickets: [
            { id: "t1", name: "Beach Pass", price: 999, quantity: 2000, remaining: 456 },
            { id: "t2", name: "VIP Zone", price: 2499, quantity: 100, remaining: 22 },
        ],
        stats: { views: 14200, saves: 1102, shares: 430, rsvps: 1800 },
        coordinates: { latitude: 15.5733, longitude: 73.7457 },
    },
    {
        id: "demo-event-06",
        title: "Afterhours",
        description: "Hard-hitting techno night at Bengaluru's most exclusive club. Resident DJs joined by a Berlin-based special guest.",
        startDate: "2026-04-26T23:00:00.000Z",
        endDate: "2026-04-27T05:00:00.000Z",
        venue: "KLTV, Bengaluru",
        location: "KLTV, Indiranagar, Bengaluru",
        city: "Bengaluru",
        hostId: "demo-host-06",
        hostName: "KLTV Bengaluru",
        coverImage: DEMO_POSTERS.afterhours,
        poster: DEMO_POSTERS.afterhours,
        image: DEMO_POSTERS.afterhours,
        lifecycle: "scheduled",
        status: "active",
        isFeatured: false,
        heatScore: 82,
        category: "club",
        tags: ["techno", "berlin", "club", "saturday"],
        tickets: [
            { id: "t1", name: "GA", price: 599, quantity: 200, remaining: 68 },
            { id: "t2", name: "Premium", price: 1199, quantity: 50, remaining: 14 },
        ],
        stats: { views: 3600, saves: 248, shares: 71, rsvps: 330 },
        coordinates: { latitude: 12.9716, longitude: 77.6412 },
    },
    {
        id: "demo-event-07",
        title: "Midnight Club",
        description: "Four of India's best indie bands perform live. Two stages, food trucks, and a cosy garden setup.",
        startDate: "2026-05-17T17:00:00.000Z",
        endDate: "2026-05-17T23:30:00.000Z",
        venue: "Tuning Fork, Mumbai",
        location: "Tuning Fork, Lower Parel, Mumbai",
        city: "Mumbai",
        hostId: "demo-host-03",
        hostName: "Bass Station India",
        coverImage: DEMO_POSTERS.midnightClub,
        poster: DEMO_POSTERS.midnightClub,
        image: DEMO_POSTERS.midnightClub,
        lifecycle: "scheduled",
        status: "active",
        isFeatured: false,
        heatScore: 71,
        category: "concert",
        tags: ["indie", "live-music", "bands", "garden"],
        tickets: [
            { id: "t1", name: "Standard", price: 799, quantity: 300, remaining: 190 },
        ],
        stats: { views: 2800, saves: 187, shares: 55, rsvps: 280 },
        coordinates: { latitude: 18.9976, longitude: 72.8304 },
    },
    {
        id: "demo-event-08",
        title: "House of Afro",
        description: "A night of smooth R&B and neo-soul. Live vocalists, a curated cocktail menu, and art on every wall.",
        startDate: "2026-05-02T21:00:00.000Z",
        endDate: "2026-05-03T02:00:00.000Z",
        venue: "Social, Koregaon Park, Pune",
        location: "Social, Koregaon Park, Pune",
        city: "Pune",
        hostId: "demo-host-02",
        hostName: "The Bund",
        coverImage: DEMO_POSTERS.houseOfAfro,
        poster: DEMO_POSTERS.houseOfAfro,
        image: DEMO_POSTERS.houseOfAfro,
        lifecycle: "scheduled",
        status: "active",
        isFeatured: false,
        heatScore: 65,
        category: "party",
        tags: ["rnb", "neo-soul", "live-vocals", "art"],
        tickets: [
            { id: "t1", name: "General", price: 499, quantity: 150, remaining: 88 },
        ],
        stats: { views: 1900, saves: 134, shares: 38, rsvps: 167 },
        coordinates: { latitude: 18.5362, longitude: 73.8942 },
    },
    {
        id: "demo-event-09",
        title: "No Signal",
        description: "A unique open-air rave set in the ruins of an old Portuguese fort in Goa. Ambient, minimal techno, and sunrise vibes.",
        startDate: "2026-05-24T23:30:00.000Z",
        endDate: "2026-05-25T07:00:00.000Z",
        venue: "Aguada Fort, Goa",
        location: "Aguada Fort, Candolim, Goa",
        city: "Goa",
        hostId: "demo-host-05",
        hostName: "Shiva Valley Goa",
        coverImage: DEMO_POSTERS.noSignal,
        poster: DEMO_POSTERS.noSignal,
        image: DEMO_POSTERS.noSignal,
        lifecycle: "live",
        status: "active",
        isFeatured: true,
        heatScore: 91,
        category: "festival",
        tags: ["outdoor", "minimal", "fort", "sunrise", "open-air"],
        tickets: [
            { id: "t1", name: "Entry", price: 1299, quantity: 500, remaining: 63 },
        ],
        stats: { views: 7700, saves: 589, shares: 192, rsvps: 620 },
        coordinates: { latitude: 15.4999, longitude: 73.7679 },
    },
    {
        id: "demo-event-10",
        title: "House of Afro",
        description: "Afrobeats, Afro-house, and dancehall hits. Bengaluru's most energetic Friday night with surprise performances.",
        startDate: "2026-05-08T22:00:00.000Z",
        endDate: "2026-05-09T04:00:00.000Z",
        venue: "Toit Brew Pub, Bengaluru",
        location: "Toit, Indiranagar, Bengaluru",
        city: "Bengaluru",
        hostId: "demo-host-06",
        hostName: "KLTV Bengaluru",
        coverImage: DEMO_POSTERS.houseOfAfro,
        poster: DEMO_POSTERS.houseOfAfro,
        image: DEMO_POSTERS.houseOfAfro,
        lifecycle: "scheduled",
        status: "active",
        isFeatured: false,
        heatScore: 78,
        category: "party",
        tags: ["afrobeats", "dancehall", "friday", "surprise"],
        tickets: [
            { id: "t1", name: "Stag", price: 699, quantity: 100, remaining: 44 },
            { id: "t2", name: "Couple", price: 1099, quantity: 60, remaining: 28 },
        ],
        stats: { views: 3300, saves: 220, shares: 64, rsvps: 310 },
        coordinates: { latitude: 12.9784, longitude: 77.6408 },
    },
];

// ── Venues ────────────────────────────────────────────────────────────────────

export const DEMO_VENUES = [
    {
        id: "demo-venue-01",
        name: "Colosseum Pune",
        displayName: "Colosseum",
        slug: "colosseum-pune",
        area: "Ishanya",
        neighborhood: "Mundhwa",
        city: "Pune",
        address: "Ishanya Mall, Off Pune Nagar Road, Mundhwa, Pune 411036",
        addressLine1: "Ishanya Mall, Off Pune Nagar Road",
        image: DEMO_POSTERS.neonDistrict,
        coverImage: DEMO_POSTERS.neonDistrict,
        coverURL: DEMO_POSTERS.neonDistrict,
        bannerImage: DEMO_POSTERS.neonDistrict,
        logoImage: DEMO_POSTERS.logoCircle,
        tags: ["nightclub", "electronic", "DJ", "dance-floor"],
        vibes: ["dark", "energetic", "underground"],
        genres: ["techno", "house", "electronic"],
        tablesAvailable: true,
        isVerified: true,
        venueType: "nightclub",
        description: "Pune's premier underground club with a state-of-the-art sound system, dynamic lighting rigs, and an intimate yet powerful dance floor.",
        whatsapp: "+919876543210",
        phone: "+912040001234",
        followers: 4821,
        hasReservation: true,
        popularityScore: 94,
        upcomingEventsCount: 3,
        nextEventDate: "2026-04-26T21:00:00.000Z",
        nextEventId: "demo-event-01",
        nextEventTitle: "Neon District",
        coordinates: { latitude: 18.5204, longitude: 73.8567 },
    },
    {
        id: "demo-venue-02",
        name: "The Bund",
        displayName: "The Bund",
        slug: "the-bund-pune",
        area: "Kalyani Nagar",
        neighborhood: "Kalyani Nagar",
        city: "Pune",
        address: "Lane 5, Kalyani Nagar, Pune 411006",
        addressLine1: "Lane 5, Kalyani Nagar",
        image: DEMO_POSTERS.aquaSundays,
        coverImage: DEMO_POSTERS.aquaSundays,
        coverURL: DEMO_POSTERS.aquaSundays,
        bannerImage: DEMO_POSTERS.aquaSundays,
        logoImage: DEMO_POSTERS.logoCircle,
        tags: ["rooftop", "lounge", "cocktails", "brunch"],
        vibes: ["chic", "romantic", "upscale"],
        genres: ["bollywood", "hip-hop", "rnb"],
        tablesAvailable: true,
        isVerified: true,
        venueType: "lounge",
        description: "An elevated rooftop lounge in the heart of Kalyani Nagar. Signature cocktails, Sunday brunches, and the city's best sunset views.",
        whatsapp: "+919876500001",
        phone: "+912040005678",
        followers: 3102,
        hasReservation: true,
        popularityScore: 88,
        upcomingEventsCount: 2,
        nextEventDate: "2026-04-27T11:00:00.000Z",
        nextEventId: "demo-event-02",
        nextEventTitle: "Aqua Sundays",
        coordinates: { latitude: 18.5362, longitude: 73.9003 },
    },
    {
        id: "demo-venue-03",
        name: "NSCI Dome Mumbai",
        displayName: "NSCI Dome",
        slug: "nsci-dome-mumbai",
        area: "Worli",
        neighborhood: "Worli",
        city: "Mumbai",
        address: "Worli Sports Club, Worli, Mumbai 400030",
        addressLine1: "Worli Sports Club, Worli",
        image: DEMO_POSTERS.redRoom,
        coverImage: DEMO_POSTERS.redRoom,
        coverURL: DEMO_POSTERS.redRoom,
        bannerImage: DEMO_POSTERS.redRoom,
        logoImage: DEMO_POSTERS.logoCircle,
        tags: ["warehouse", "large-venue", "concert", "festival"],
        vibes: ["raw", "industrial", "massive"],
        genres: ["dnb", "bass", "indie", "live-music"],
        tablesAvailable: false,
        isVerified: true,
        venueType: "concert-hall",
        description: "Mumbai's iconic domed venue. Host to India's most legendary music nights, with capacity for 3,000+ guests and a world-class sound system.",
        phone: "+912240001111",
        followers: 9420,
        hasReservation: false,
        popularityScore: 97,
        upcomingEventsCount: 2,
        nextEventDate: "2026-05-03T22:00:00.000Z",
        nextEventId: "demo-event-03",
        nextEventTitle: "Red Room",
        coordinates: { latitude: 19.0176, longitude: 72.8143 },
    },
    {
        id: "demo-venue-04",
        name: "Howzat Bar & Kitchen",
        displayName: "Howzat Bandra",
        slug: "howzat-bandra",
        area: "Bandra West",
        neighborhood: "Bandra",
        city: "Mumbai",
        address: "14th Road, Khar West, Mumbai 400052",
        addressLine1: "14th Road, Khar West",
        image: DEMO_POSTERS.velvetNights,
        coverImage: DEMO_POSTERS.velvetNights,
        coverURL: DEMO_POSTERS.velvetNights,
        bannerImage: DEMO_POSTERS.velvetNights,
        logoImage: DEMO_POSTERS.logoCircle,
        tags: ["rooftop", "jazz", "intimate", "cocktails"],
        vibes: ["cosy", "romantic", "jazz"],
        genres: ["jazz", "soul", "acoustic"],
        tablesAvailable: true,
        isVerified: true,
        venueType: "bar",
        description: "Bandra's favourite rooftop bar with jaw-dropping skyline views, a curated cocktail menu, and intimate live music sessions.",
        whatsapp: "+919876512345",
        phone: "+912266001234",
        followers: 2214,
        hasReservation: true,
        popularityScore: 79,
        upcomingEventsCount: 1,
        nextEventDate: "2026-04-25T18:30:00.000Z",
        nextEventId: "demo-event-04",
        nextEventTitle: "Velvet Nights",
        coordinates: { latitude: 19.0596, longitude: 72.8295 },
    },
    {
        id: "demo-venue-05",
        name: "Shiva Valley Goa",
        displayName: "Shiva Valley",
        slug: "shiva-valley-goa",
        area: "Anjuna",
        neighborhood: "Anjuna",
        city: "Goa",
        address: "Anjuna Beach Road, Anjuna, North Goa 403509",
        addressLine1: "Anjuna Beach Road",
        image: DEMO_POSTERS.eclipse,
        coverImage: DEMO_POSTERS.eclipse,
        coverURL: DEMO_POSTERS.eclipse,
        bannerImage: DEMO_POSTERS.eclipse,
        logoImage: DEMO_POSTERS.logoCircle,
        tags: ["beach", "psytrance", "outdoor", "festival"],
        vibes: ["spiritual", "psychedelic", "free-spirit"],
        genres: ["psytrance", "goa-trance", "ambient"],
        tablesAvailable: false,
        isVerified: true,
        venueType: "beach-club",
        description: "The legendary Goa trance venue on Anjuna Beach. Where the music never stops and the sunrises are sacred. International artists, local legends.",
        phone: "+918322001234",
        followers: 12890,
        hasReservation: false,
        popularityScore: 99,
        upcomingEventsCount: 2,
        nextEventDate: "2026-05-10T20:00:00.000Z",
        nextEventId: "demo-event-05",
        nextEventTitle: "Eclipse",
        coordinates: { latitude: 15.5733, longitude: 73.7457 },
    },
    {
        id: "demo-venue-06",
        name: "KLTV Bengaluru",
        displayName: "KLTV",
        slug: "kltv-bengaluru",
        area: "Indiranagar",
        neighborhood: "Indiranagar",
        city: "Bengaluru",
        address: "100 Feet Road, Indiranagar, Bengaluru 560038",
        addressLine1: "100 Feet Road, Indiranagar",
        image: DEMO_POSTERS.afterhours,
        coverImage: DEMO_POSTERS.afterhours,
        coverURL: DEMO_POSTERS.afterhours,
        bannerImage: DEMO_POSTERS.afterhours,
        logoImage: DEMO_POSTERS.logoCircle,
        tags: ["club", "techno", "premium", "exclusive"],
        vibes: ["dark", "premium", "serious"],
        genres: ["techno", "minimal", "hard-techno"],
        tablesAvailable: true,
        isVerified: true,
        venueType: "nightclub",
        description: "Bengaluru's most exclusive techno club. Minimal decor, maximum sound. Berlin-inspired, Indiranagar-born.",
        whatsapp: "+917760001234",
        phone: "+918040001234",
        followers: 6341,
        hasReservation: true,
        popularityScore: 85,
        upcomingEventsCount: 2,
        nextEventDate: "2026-04-26T23:00:00.000Z",
        nextEventId: "demo-event-06",
        nextEventTitle: "Afterhours",
        coordinates: { latitude: 12.9716, longitude: 77.6412 },
    },
];

// ── Orders / Tickets ──────────────────────────────────────────────────────────

export const DEMO_ORDERS = [
    {
        id: "demo-order-01",
        userId: "demo-user-001",
        userEmail: "demo@c1rcle.in",
        userName: "Arjun Mehta",
        eventId: "demo-event-01",
        eventTitle: "Neon District",
        eventDate: "2026-04-26T21:00:00.000Z",
        eventStartDate: "2026-04-26T21:00:00.000Z",
        eventTime: "9:00 PM",
        eventCoverImage: DEMO_POSTERS.neonDistrict,
        venueLocation: "Ishanya Mall, Pune",
        hostName: "Colosseum Pune",
        accentColor: "#F44A22",
        status: "confirmed" as const,
        tickets: [
            {
                tierId: "t2",
                tierName: "Regular Entry",
                quantity: 2,
                price: 799,
                subtotal: 1598,
                entryType: "general",
                ticketId: "demo-ticket-001a",
                isClaimed: false,
                claimedBy: null,
            },
        ],
        totalAmount: 1598,
        currency: "INR",
        createdAt: "2026-04-15T12:30:00.000Z",
        updatedAt: "2026-04-15T12:31:00.000Z",
        confirmedAt: "2026-04-15T12:31:00.000Z",
        qrData: JSON.stringify({ orderId: "demo-order-01", eventId: "demo-event-01" }),
        qrCodes: [
            { ticketId: "demo-ticket-001a", ticketIndex: 0, qrCode: JSON.stringify({ orderId: "demo-order-01", index: 0 }), isUsed: false },
            { ticketId: "demo-ticket-001b", ticketIndex: 1, qrCode: JSON.stringify({ orderId: "demo-order-01", index: 1 }), isUsed: false },
        ],
        isClaimed: false,
        isRSVP: false,
        source: "mobile",
    },
    {
        id: "demo-order-02",
        userId: "demo-user-001",
        userEmail: "demo@c1rcle.in",
        userName: "Arjun Mehta",
        eventId: "demo-event-05",
        eventTitle: "Eclipse",
        eventDate: "2026-05-10T20:00:00.000Z",
        eventStartDate: "2026-05-10T20:00:00.000Z",
        eventTime: "8:00 PM",
        eventCoverImage: DEMO_POSTERS.eclipse,
        venueLocation: "Anjuna Beach, North Goa",
        hostName: "Shiva Valley Goa",
        accentColor: "#7C3AED",
        status: "confirmed" as const,
        tickets: [
            {
                tierId: "t2",
                tierName: "VIP Zone",
                quantity: 1,
                price: 2499,
                subtotal: 2499,
                entryType: "vip",
                ticketId: "demo-ticket-002a",
                isClaimed: false,
                claimedBy: null,
            },
        ],
        totalAmount: 2499,
        currency: "INR",
        createdAt: "2026-04-10T09:00:00.000Z",
        updatedAt: "2026-04-10T09:01:00.000Z",
        confirmedAt: "2026-04-10T09:01:00.000Z",
        qrData: JSON.stringify({ orderId: "demo-order-02", eventId: "demo-event-05" }),
        qrCodes: [
            { ticketId: "demo-ticket-002a", ticketIndex: 0, qrCode: JSON.stringify({ orderId: "demo-order-02", index: 0 }), isUsed: false },
        ],
        isClaimed: false,
        isRSVP: false,
        source: "mobile",
    },
    {
        id: "demo-order-03",
        userId: "demo-user-001",
        userEmail: "demo@c1rcle.in",
        userName: "Arjun Mehta",
        eventId: "demo-event-03",
        eventTitle: "Red Room",
        eventDate: "2026-05-03T22:00:00.000Z",
        eventStartDate: "2026-05-03T22:00:00.000Z",
        eventTime: "10:00 PM",
        eventCoverImage: DEMO_POSTERS.redRoom,
        venueLocation: "NSCI Dome, Worli, Mumbai",
        hostName: "Bass Station India",
        accentColor: "#0EA5E9",
        status: "checked_in" as const,
        tickets: [
            {
                tierId: "t1",
                tierName: "GA",
                quantity: 1,
                price: 699,
                subtotal: 699,
                entryType: "general",
                ticketId: "demo-ticket-003a",
                isClaimed: true,
                claimedBy: { uid: "demo-user-001", name: "Arjun Mehta", email: "demo@c1rcle.in" },
            },
        ],
        totalAmount: 699,
        currency: "INR",
        createdAt: "2026-03-28T18:00:00.000Z",
        updatedAt: "2026-04-14T22:30:00.000Z",
        confirmedAt: "2026-03-28T18:01:00.000Z",
        qrData: JSON.stringify({ orderId: "demo-order-03", eventId: "demo-event-03" }),
        qrCodes: [
            { ticketId: "demo-ticket-003a", ticketIndex: 0, qrCode: JSON.stringify({ orderId: "demo-order-03", index: 0 }), isUsed: true },
        ],
        isClaimed: true,
        isRSVP: false,
        source: "mobile",
    },
];

// ── Notifications ─────────────────────────────────────────────────────────────

export const DEMO_NOTIFICATIONS = [
    {
        id: "demo-notif-01",
        type: "ticket_purchased" as const,
        title: "Booking Confirmed!",
        body: "Your 2 tickets for Neon District are confirmed. See you on 26 Apr!",
        imageUrl: DEMO_POSTERS.neonDistrict,
        data: { eventId: "demo-event-01", orderId: "demo-order-01" },
        read: false,
        createdAt: new Date("2026-04-15T12:31:00.000Z"),
    },
    {
        id: "demo-notif-02",
        type: "event_reminder" as const,
        title: "Tonight: Neon District!",
        body: "Your event starts in 3 hours at Ishanya Mall. Don't forget your ticket QR code.",
        imageUrl: DEMO_POSTERS.neonDistrict,
        data: { eventId: "demo-event-01" },
        read: false,
        createdAt: new Date("2026-04-26T18:00:00.000Z"),
    },
    {
        id: "demo-notif-03",
        type: "dm_request" as const,
        title: "New Connection Request",
        body: "Priya Sharma wants to connect with you from Eclipse.",
        imageUrl: "https://i.pravatar.cc/200?img=5",
        data: { userId: "demo-dating-02" },
        read: false,
        createdAt: new Date("2026-04-14T20:00:00.000Z"),
    },
    {
        id: "demo-notif-04",
        type: "ticket_purchased" as const,
        title: "VIP Confirmed!",
        body: "Your VIP Zone ticket for Eclipse is locked in. Get ready for an epic night!",
        imageUrl: DEMO_POSTERS.eclipse,
        data: { eventId: "demo-event-05", orderId: "demo-order-02" },
        read: true,
        createdAt: new Date("2026-04-10T09:01:00.000Z"),
    },
    {
        id: "demo-notif-05",
        type: "event_changed" as const,
        title: "Venue Update: Red Room",
        body: "Doors now open at 10 PM instead of 9 PM. Gates: NSCI Dome, Gate 2.",
        imageUrl: DEMO_POSTERS.redRoom,
        data: { eventId: "demo-event-03" },
        read: true,
        createdAt: new Date("2026-04-12T14:00:00.000Z"),
    },
];

// ── Dating Profiles ───────────────────────────────────────────────────────────

export const DEMO_DATING_PROFILES = [
    {
        userId: "demo-dating-01",
        displayName: "Ananya Kapoor",
        photoURL: "https://i.pravatar.cc/400?img=47",
        bio: "DJ by night, designer by day. I live for that moment when the bass drops just right 🎧",
        city: "Pune",
        vibeTags: ["techno", "art", "travel", "yoga"],
        isVerified: true,
        sharedEventId: "demo-event-01",
        sharedEventTitle: "Neon District",
        sharedEventDate: "2026-04-26T21:00:00.000Z",
        sharedEventCover: DEMO_POSTERS.neonDistrict,
    },
    {
        userId: "demo-dating-02",
        displayName: "Priya Sharma",
        photoURL: "https://i.pravatar.cc/400?img=5",
        bio: "Goa is home. Chasing sunrises and good music. Always down for an adventure 🌊",
        city: "Goa",
        vibeTags: ["psytrance", "beach", "photography", "hiking"],
        isVerified: true,
        sharedEventId: "demo-event-05",
        sharedEventTitle: "Eclipse",
        sharedEventDate: "2026-05-10T20:00:00.000Z",
        sharedEventCover: DEMO_POSTERS.eclipse,
    },
    {
        userId: "demo-dating-03",
        displayName: "Kavya Reddy",
        photoURL: "https://i.pravatar.cc/400?img=9",
        bio: "Bengaluru techno girlie. Coffee, code, and club nights. Looking for someone to split cab rides with 🚕",
        city: "Bengaluru",
        vibeTags: ["techno", "coffee", "coding", "cats"],
        isVerified: false,
        sharedEventId: "demo-event-06",
        sharedEventTitle: "Afterhours",
        sharedEventDate: "2026-04-26T23:00:00.000Z",
        sharedEventCover: DEMO_POSTERS.afterhours,
    },
    {
        userId: "demo-dating-04",
        displayName: "Siddharth Nair",
        photoURL: "https://i.pravatar.cc/400?img=12",
        bio: "Music producer. I've probably played the set you loved last Saturday. Let's grab a drink 🥃",
        city: "Mumbai",
        vibeTags: ["music-production", "football", "cocktails", "jazz"],
        isVerified: true,
        sharedEventId: "demo-event-03",
        sharedEventTitle: "Red Room",
        sharedEventDate: "2026-05-03T22:00:00.000Z",
        sharedEventCover: DEMO_POSTERS.redRoom,
    },
    {
        userId: "demo-dating-05",
        displayName: "Rhea D'Souza",
        photoURL: "https://i.pravatar.cc/400?img=44",
        bio: "Goa local. I know all the secret spots that aren't on Google Maps. Also, I make excellent pasta 🍝",
        city: "Goa",
        vibeTags: ["goa-trance", "cooking", "water-sports", "astrology"],
        isVerified: true,
        sharedEventId: "demo-event-09",
        sharedEventTitle: "No Signal",
        sharedEventDate: "2026-05-24T23:30:00.000Z",
        sharedEventCover: DEMO_POSTERS.noSignal,
    },
];

// ── Matches ───────────────────────────────────────────────────────────────────

export const DEMO_MATCHES = [
    {
        id: "demo-match-01",
        otherUserId: "demo-dating-01",
        displayName: "Ananya Kapoor",
        photoURL: "https://i.pravatar.cc/400?img=47",
        sharedEventTitle: "Neon District",
        matchedAt: "2026-04-16T09:00:00.000Z",
        conversationId: "demo-convo-01",
    },
    {
        id: "demo-match-02",
        otherUserId: "demo-dating-04",
        displayName: "Siddharth Nair",
        photoURL: "https://i.pravatar.cc/400?img=12",
        sharedEventTitle: "Red Room",
        matchedAt: "2026-04-14T22:00:00.000Z",
        conversationId: "demo-convo-02",
    },
];

// ── User Profile ──────────────────────────────────────────────────────────────

export const DEMO_USER_PROFILE = {
    uid: "demo-user-001",
    email: "demo@c1rcle.in",
    displayName: "Arjun Mehta",
    photoURL: "https://i.pravatar.cc/400?img=68",
    bio: "Always at the best events. Pune → Mumbai → Goa. Sound chaser 🎵",
    city: "Pune",
    phone: "+919876543210",
    gender: "male" as const,
    dateOfBirth: "1998-03-14",
    createdAt: "2025-01-10T10:00:00.000Z",
    updatedAt: "2026-04-15T08:00:00.000Z",
    eventsAttended: 24,
    connections: 38,
    vibeTags: ["techno", "travel", "photography", "food"],
    isVerified: true,
    isPremium: false,
};

// ── Social Profile ────────────────────────────────────────────────────────────

export const DEMO_SOCIAL_PROFILE = {
    state: "verified" as const,
    photos: [
        "https://i.pravatar.cc/400?img=68",
        "https://picsum.photos/seed/arjun1/400/500",
        "https://picsum.photos/seed/arjun2/400/500",
    ],
    primaryPhotoIndex: 0,
    city: "Pune",
    interestedIn: ["female"] as ("male" | "female" | "nonbinary" | "everyone")[],
    ageRangeMin: 20,
    ageRangeMax: 30,
    height: 178,
    smoking: "never",
    drinking: "socially",
    sexuality: "straight",
    lookingFor: ["relationship", "friends"],
    isVisible: true,
    completedAt: "2025-02-01T12:00:00.000Z",
    verifiedAt: "2025-02-03T09:00:00.000Z",
    verificationPhotoHash: "abcdef1234567890abcdef1234567890",
};

// ── Additional Dating Profiles (more swipe cards) ─────────────────────────────

export const DEMO_EXTRA_DATING_PROFILES = [
    {
        userId: "demo-dating-06",
        displayName: "Meera Joshi",
        photoURL: "https://i.pravatar.cc/400?img=32",
        bio: "Classically trained vocalist by day, raave animal by night. If you know good food spots in Pune, let's talk 🍜",
        city: "Pune",
        vibeTags: ["classical", "rave", "foodie", "brunch"],
        isVerified: true,
        sharedEventId: "demo-event-02",
        sharedEventTitle: "Aqua Sundays",
        sharedEventDate: "2026-04-27T11:00:00.000Z",
        sharedEventCover: DEMO_POSTERS.aquaSundays,
    },
    {
        userId: "demo-dating-07",
        displayName: "Rohan Verma",
        photoURL: "https://i.pravatar.cc/400?img=15",
        bio: "Photographer. I spend half my time behind a lens and the other half on a dance floor. Shoot me a DM 📷",
        city: "Mumbai",
        vibeTags: ["photography", "dnb", "film", "coffee"],
        isVerified: true,
        sharedEventId: "demo-event-03",
        sharedEventTitle: "Red Room",
        sharedEventDate: "2026-05-03T22:00:00.000Z",
        sharedEventCover: DEMO_POSTERS.redRoom,
    },
    {
        userId: "demo-dating-08",
        displayName: "Nisha Pillai",
        photoURL: "https://i.pravatar.cc/400?img=20",
        bio: "Finance by week, festival by weekend. Currently planning a Goa trip for every month this year 🌴",
        city: "Mumbai",
        vibeTags: ["festivals", "yoga", "investing", "beach"],
        isVerified: false,
        sharedEventId: "demo-event-05",
        sharedEventTitle: "Eclipse",
        sharedEventDate: "2026-05-10T20:00:00.000Z",
        sharedEventCover: DEMO_POSTERS.eclipse,
    },
    {
        userId: "demo-dating-09",
        displayName: "Aryan Malhotra",
        photoURL: "https://i.pravatar.cc/400?img=57",
        bio: "Techno missionary. Spreading the good word of 4/4 beats across Bengaluru. Also I make great pasta 🍝",
        city: "Bengaluru",
        vibeTags: ["techno", "cooking", "cycling", "minimal"],
        isVerified: true,
        sharedEventId: "demo-event-06",
        sharedEventTitle: "Afterhours",
        sharedEventDate: "2026-04-26T23:00:00.000Z",
        sharedEventCover: DEMO_POSTERS.afterhours,
    },
    {
        userId: "demo-dating-10",
        displayName: "Zara Khan",
        photoURL: "https://i.pravatar.cc/400?img=25",
        bio: "Art director who moonlights as a DJ. Eclectic taste, good playlists, bad jokes. Come find me at the booth 🎧",
        city: "Mumbai",
        vibeTags: ["art", "djing", "design", "afrobeats"],
        isVerified: true,
        sharedEventId: "demo-event-10",
        sharedEventTitle: "House of Afro",
        sharedEventDate: "2026-05-08T22:00:00.000Z",
        sharedEventCover: DEMO_POSTERS.houseOfAfro,
    },
    {
        userId: "demo-dating-11",
        displayName: "Ishaan Patel",
        photoURL: "https://i.pravatar.cc/400?img=61",
        bio: "Startup guy vibing to indie. Weekend = live music + long drives. Goa next month, anyone? 🚗",
        city: "Pune",
        vibeTags: ["indie", "entrepreneurship", "roadtrips", "craft-beer"],
        isVerified: false,
        sharedEventId: "demo-event-07",
        sharedEventTitle: "Midnight Club",
        sharedEventDate: "2026-05-17T17:00:00.000Z",
        sharedEventCover: DEMO_POSTERS.midnightClub,
    },
    {
        userId: "demo-dating-12",
        displayName: "Tanvi Desai",
        photoURL: "https://i.pravatar.cc/400?img=36",
        bio: "Dancer. Theatre kid. Will cry at a good bassline. Passionate about sustainable fashion and loud music 🪩",
        city: "Pune",
        vibeTags: ["dance", "theatre", "sustainability", "house"],
        isVerified: true,
        sharedEventId: "demo-event-08",
        sharedEventTitle: "House of Afro",
        sharedEventDate: "2026-05-02T21:00:00.000Z",
        sharedEventCover: DEMO_POSTERS.houseOfAfro,
    },
    {
        userId: "demo-dating-13",
        displayName: "Vikram Rao",
        photoURL: "https://i.pravatar.cc/400?img=70",
        bio: "Chef turned club-goer. My idea of a perfect night: good food at 8pm, underground music until 5am ☀️",
        city: "Goa",
        vibeTags: ["food", "psytrance", "sunrise", "cooking"],
        isVerified: true,
        sharedEventId: "demo-event-09",
        sharedEventTitle: "No Signal",
        sharedEventDate: "2026-05-24T23:30:00.000Z",
        sharedEventCover: DEMO_POSTERS.noSignal,
    },
];

// ── Extended Dating Profiles Pool (keeps swipe deck full during demo) ─────────

export const DEMO_EXTENDED_PROFILES = [
    {
        userId: "demo-dating-14",
        displayName: "Aisha Rao",
        photoURL: "https://i.pravatar.cc/400?img=1",
        bio: "Content creator & weekend raver. If my reel didn't get 10K views I'm at a rave instead 🎥",
        city: "Mumbai",
        vibeTags: ["content", "techno", "reels", "coffee"],
        isVerified: true,
        sharedEventId: "demo-event-03",
        sharedEventTitle: "Red Room",
        sharedEventDate: "2026-05-03T22:00:00.000Z",
        sharedEventCover: DEMO_POSTERS.redRoom,
    },
    {
        userId: "demo-dating-15",
        displayName: "Karan Mehta",
        photoURL: "https://i.pravatar.cc/400?img=3",
        bio: "Architect who builds by day and breaks dance floors by night. Brutalist spaces, maximal beats 🏛️",
        city: "Bengaluru",
        vibeTags: ["architecture", "techno", "design", "chess"],
        isVerified: true,
        sharedEventId: "demo-event-06",
        sharedEventTitle: "Afterhours",
        sharedEventDate: "2026-04-26T23:00:00.000Z",
        sharedEventCover: DEMO_POSTERS.afterhours,
    },
    {
        userId: "demo-dating-16",
        displayName: "Diya Pillai",
        photoURL: "https://i.pravatar.cc/400?img=10",
        bio: "Marine biologist obsessed with underwater acoustics and bass frequencies. Basically the same thing 🐠",
        city: "Goa",
        vibeTags: ["ocean", "bass", "science", "diving"],
        isVerified: false,
        sharedEventId: "demo-event-05",
        sharedEventTitle: "Eclipse",
        sharedEventDate: "2026-05-10T20:00:00.000Z",
        sharedEventCover: DEMO_POSTERS.eclipse,
    },
    {
        userId: "demo-dating-17",
        displayName: "Nikhil Sharma",
        photoURL: "https://i.pravatar.cc/400?img=52",
        bio: "Runs a record label out of a Koregaon Park flat. Very serious about music, very unserious about everything else 🎵",
        city: "Pune",
        vibeTags: ["records", "house", "label", "vinyl"],
        isVerified: true,
        sharedEventId: "demo-event-01",
        sharedEventTitle: "Neon District",
        sharedEventDate: "2026-04-26T21:00:00.000Z",
        sharedEventCover: DEMO_POSTERS.neonDistrict,
    },
    {
        userId: "demo-dating-18",
        displayName: "Pooja Nair",
        photoURL: "https://i.pravatar.cc/400?img=16",
        bio: "Yoga teacher who DJs on weekends. Yes I can go from 60bpm to 140bpm. It's called range 🧘",
        city: "Goa",
        vibeTags: ["yoga", "djing", "wellness", "morning-raves"],
        isVerified: true,
        sharedEventId: "demo-event-09",
        sharedEventTitle: "No Signal",
        sharedEventDate: "2026-05-24T23:30:00.000Z",
        sharedEventCover: DEMO_POSTERS.noSignal,
    },
    {
        userId: "demo-dating-19",
        displayName: "Aditya Bose",
        photoURL: "https://i.pravatar.cc/400?img=56",
        bio: "Sound engineer. I make sure your favourite DJ actually sounds good. You're welcome 🎚️",
        city: "Mumbai",
        vibeTags: ["audio", "live-sound", "concerts", "gear"],
        isVerified: false,
        sharedEventId: "demo-event-07",
        sharedEventTitle: "Midnight Club",
        sharedEventDate: "2026-05-17T17:00:00.000Z",
        sharedEventCover: DEMO_POSTERS.midnightClub,
    },
    {
        userId: "demo-dating-20",
        displayName: "Simran Kaur",
        photoURL: "https://i.pravatar.cc/400?img=27",
        bio: "Lawyer who only takes cases she's passionate about. Currently most passionate about getting to Goa next weekend 🌊",
        city: "Mumbai",
        vibeTags: ["law", "beach", "psytrance", "mischief"],
        isVerified: true,
        sharedEventId: "demo-event-05",
        sharedEventTitle: "Eclipse",
        sharedEventDate: "2026-05-10T20:00:00.000Z",
        sharedEventCover: DEMO_POSTERS.eclipse,
    },
    {
        userId: "demo-dating-21",
        displayName: "Rahul Krishnan",
        photoURL: "https://i.pravatar.cc/400?img=65",
        bio: "Startup CTO who codes to techno. My standups are exactly 4 minutes. Like a DJ transition 💻",
        city: "Bengaluru",
        vibeTags: ["startup", "coding", "techno", "cycling"],
        isVerified: true,
        sharedEventId: "demo-event-10",
        sharedEventTitle: "House of Afro",
        sharedEventDate: "2026-05-08T22:00:00.000Z",
        sharedEventCover: DEMO_POSTERS.houseOfAfro,
    },
    {
        userId: "demo-dating-22",
        displayName: "Nandita Roy",
        photoURL: "https://i.pravatar.cc/400?img=40",
        bio: "Documentary filmmaker. Currently making a film about India's underground music scene. Maybe you're in it 🎬",
        city: "Mumbai",
        vibeTags: ["film", "documentary", "electronic", "storytelling"],
        isVerified: true,
        sharedEventId: "demo-event-03",
        sharedEventTitle: "Red Room",
        sharedEventDate: "2026-05-03T22:00:00.000Z",
        sharedEventCover: DEMO_POSTERS.redRoom,
    },
    {
        userId: "demo-dating-23",
        displayName: "Yash Agarwal",
        photoURL: "https://i.pravatar.cc/400?img=54",
        bio: "Finance bro by week, festival bro by weekend. The two identities are completely incompatible and I love it 📊",
        city: "Mumbai",
        vibeTags: ["finance", "festivals", "tennis", "whisky"],
        isVerified: false,
        sharedEventId: "demo-event-04",
        sharedEventTitle: "Velvet Nights",
        sharedEventDate: "2026-04-25T18:30:00.000Z",
        sharedEventCover: DEMO_POSTERS.velvetNights,
    },
    {
        userId: "demo-dating-24",
        displayName: "Lavanya Menon",
        photoURL: "https://i.pravatar.cc/400?img=41",
        bio: "Fashion designer who treats the dance floor as her runway. Expect outstanding outfits and questionable dance moves 💃",
        city: "Bengaluru",
        vibeTags: ["fashion", "design", "afrobeats", "art"],
        isVerified: true,
        sharedEventId: "demo-event-10",
        sharedEventTitle: "House of Afro",
        sharedEventDate: "2026-05-08T22:00:00.000Z",
        sharedEventCover: DEMO_POSTERS.houseOfAfro,
    },
    {
        userId: "demo-dating-25",
        displayName: "Dev Malhotra",
        photoURL: "https://i.pravatar.cc/400?img=59",
        bio: "Travel photographer. 40 countries. Best lighting: golden hour at a festival. Looking for a co-pilot ✈️",
        city: "Goa",
        vibeTags: ["travel", "photography", "festivals", "adventure"],
        isVerified: true,
        sharedEventId: "demo-event-09",
        sharedEventTitle: "No Signal",
        sharedEventDate: "2026-05-24T23:30:00.000Z",
        sharedEventCover: DEMO_POSTERS.noSignal,
    },
    {
        userId: "demo-dating-26",
        displayName: "Shreya Iyer",
        photoURL: "https://i.pravatar.cc/400?img=28",
        bio: "Sommelier who secretly loves a ₹200 cocktail at a rave more than a ₹2000 bottle at a restaurant 🍷",
        city: "Pune",
        vibeTags: ["wine", "rave", "food", "rooftop"],
        isVerified: false,
        sharedEventId: "demo-event-02",
        sharedEventTitle: "Aqua Sundays",
        sharedEventDate: "2026-04-27T11:00:00.000Z",
        sharedEventCover: DEMO_POSTERS.aquaSundays,
    },
    {
        userId: "demo-dating-27",
        displayName: "Vikrant Singh",
        photoURL: "https://i.pravatar.cc/400?img=62",
        bio: "Tattoo artist and weekend DJ. My forearms look better than my mixes but both are improving 🎨",
        city: "Mumbai",
        vibeTags: ["tattoos", "djing", "art", "motorcycles"],
        isVerified: true,
        sharedEventId: "demo-event-01",
        sharedEventTitle: "Neon District",
        sharedEventDate: "2026-04-26T21:00:00.000Z",
        sharedEventCover: DEMO_POSTERS.neonDistrict,
    },
    {
        userId: "demo-dating-28",
        displayName: "Preeti Chakraborty",
        photoURL: "https://i.pravatar.cc/400?img=33",
        bio: "Neuroscientist studying how music affects dopamine. Research conclusion: go to more raves 🧠",
        city: "Bengaluru",
        vibeTags: ["neuroscience", "music", "research", "hiking"],
        isVerified: true,
        sharedEventId: "demo-event-06",
        sharedEventTitle: "Afterhours",
        sharedEventDate: "2026-04-26T23:00:00.000Z",
        sharedEventCover: DEMO_POSTERS.afterhours,
    },
    {
        userId: "demo-dating-29",
        displayName: "Sameer Qureshi",
        photoURL: "https://i.pravatar.cc/400?img=66",
        bio: "Hospitality manager — I literally run nightclubs. Off the clock I just want to enjoy one 🥂",
        city: "Goa",
        vibeTags: ["hospitality", "nightlife", "travel", "food"],
        isVerified: true,
        sharedEventId: "demo-event-05",
        sharedEventTitle: "Eclipse",
        sharedEventDate: "2026-05-10T20:00:00.000Z",
        sharedEventCover: DEMO_POSTERS.eclipse,
    },
    {
        userId: "demo-dating-30",
        displayName: "Riya Desai",
        photoURL: "https://i.pravatar.cc/400?img=43",
        bio: "Startup founder, terrible cook, excellent taste in music. Two out of three isn't bad 🚀",
        city: "Pune",
        vibeTags: ["startup", "indie", "hiking", "books"],
        isVerified: false,
        sharedEventId: "demo-event-07",
        sharedEventTitle: "Midnight Club",
        sharedEventDate: "2026-05-17T17:00:00.000Z",
        sharedEventCover: DEMO_POSTERS.midnightClub,
    },
    {
        userId: "demo-dating-31",
        displayName: "Arjun Tiwari",
        photoURL: "https://i.pravatar.cc/400?img=71",
        bio: "IIT grad turned music journalist. Writing about subcultures nobody reads but everybody lives in ✍️",
        city: "Mumbai",
        vibeTags: ["writing", "journalism", "indie", "dnb"],
        isVerified: true,
        sharedEventId: "demo-event-03",
        sharedEventTitle: "Red Room",
        sharedEventDate: "2026-05-03T22:00:00.000Z",
        sharedEventCover: DEMO_POSTERS.redRoom,
    },
    {
        userId: "demo-dating-32",
        displayName: "Neha Kulkarni",
        photoURL: "https://i.pravatar.cc/400?img=38",
        bio: "Graphic novelist who illustrates the world she wants to live in. Spoiler: it has better music than yours 🎨",
        city: "Pune",
        vibeTags: ["illustration", "comics", "house", "cats"],
        isVerified: true,
        sharedEventId: "demo-event-08",
        sharedEventTitle: "House of Afro",
        sharedEventDate: "2026-05-02T21:00:00.000Z",
        sharedEventCover: DEMO_POSTERS.houseOfAfro,
    },
    {
        userId: "demo-dating-33",
        displayName: "Kartik Patel",
        photoURL: "https://i.pravatar.cc/400?img=64",
        bio: "Professional surfer, amateur human. Goa → Bali → Goa. The migration pattern of my people 🏄",
        city: "Goa",
        vibeTags: ["surfing", "beach", "psytrance", "meditation"],
        isVerified: true,
        sharedEventId: "demo-event-09",
        sharedEventTitle: "No Signal",
        sharedEventDate: "2026-05-24T23:30:00.000Z",
        sharedEventCover: DEMO_POSTERS.noSignal,
    },
];

// ── Event Group Chats ─────────────────────────────────────────────────────────

export interface DemoEventChat {
    id: string;
    eventId: string;
    eventTitle: string;
    eventCover: string;
    eventDate: string;
    lastMessage: string;
    lastMessageSender: string;
    lastMessageTime: string;
    unreadCount: number;
    participantCount: number;
    isLive: boolean;
    activeAvatars: string[];
}

export const DEMO_EVENT_CHATS: DemoEventChat[] = [
    {
        id: "chat-demo-event-01",
        eventId: "demo-event-01",
        eventTitle: "Neon District",
        eventCover: DEMO_POSTERS.neonDistrict,
        eventDate: "2026-04-26T21:00:00.000Z",
        lastMessage: "Stage two opens at 10:30. Meet near the north entrance?",
        lastMessageSender: "David S.",
        lastMessageTime: "2026-06-05T17:20:00.000Z",
        unreadCount: 12,
        participantCount: 214,
        isLive: false,
        activeAvatars: [
            "https://i.pravatar.cc/60?img=47",
            "https://i.pravatar.cc/60?img=32",
            "https://i.pravatar.cc/60?img=68",
        ],
    },
    {
        id: "chat-demo-event-05",
        eventId: "demo-event-05",
        eventTitle: "Eclipse",
        eventCover: DEMO_POSTERS.eclipse,
        eventDate: "2026-05-10T20:00:00.000Z",
        lastMessage: "Anyone else driving down from Pune on Friday morning?",
        lastMessageSender: "Mia M.",
        lastMessageTime: "2026-06-05T11:05:00.000Z",
        unreadCount: 4,
        participantCount: 456,
        isLive: false,
        activeAvatars: [
            "https://i.pravatar.cc/60?img=5",
            "https://i.pravatar.cc/60?img=15",
            "https://i.pravatar.cc/60?img=20",
        ],
    },
    {
        id: "chat-demo-event-03",
        eventId: "demo-event-03",
        eventTitle: "Red Room",
        eventCover: DEMO_POSTERS.redRoom,
        eventDate: "2026-05-03T22:00:00.000Z",
        lastMessage: "Final set times and entry details are now posted.",
        lastMessageSender: "Bass Station",
        lastMessageTime: "2026-06-04T20:00:00.000Z",
        unreadCount: 0,
        participantCount: 880,
        isLive: false,
        activeAvatars: [
            "https://i.pravatar.cc/60?img=12",
            "https://i.pravatar.cc/60?img=15",
        ],
    },
];

// ── Private / DM Conversations ────────────────────────────────────────────────

export interface DemoPrivateChat {
    id: string;
    otherUserId: string;
    otherUserName: string;
    otherUserAvatar: string;
    isVerified: boolean;
    sharedEventTitle: string;
    lastMessage: string;
    lastMessageTime: string;
    unreadCount: number;
    isOnline: boolean;
}

export const DEMO_PRIVATE_CHATS: DemoPrivateChat[] = [
    {
        id: "dm-demo-01",
        otherUserId: "demo-dating-01",
        otherUserName: "David Smith",
        otherUserAvatar: "https://i.pravatar.cc/200?img=12",
        isVerified: true,
        sharedEventTitle: "Cinema Under the Stars",
        lastMessage: "So, are we still going to watch that movie tonight?",
        lastMessageTime: "2026-06-05T18:42:00.000Z",
        unreadCount: 2,
        isOnline: true,
    },
    {
        id: "dm-demo-02",
        otherUserId: "demo-dating-04",
        otherUserName: "Charlie Brown",
        otherUserAvatar: "https://i.pravatar.cc/200?img=11",
        isVerified: true,
        sharedEventTitle: "Late Night Screening",
        lastMessage: "I can't believe that ending, totally unexpected!",
        lastMessageTime: "2026-06-05T12:54:00.000Z",
        unreadCount: 0,
        isOnline: false,
    },
    {
        id: "dm-demo-03",
        otherUserId: "demo-dating-07",
        otherUserName: "Alice Johnson",
        otherUserAvatar: "https://i.pravatar.cc/200?img=47",
        isVerified: true,
        sharedEventTitle: "Midnight Club",
        lastMessage: "Hey, did you finish the series I recommended?",
        lastMessageTime: "2026-06-04T21:18:00.000Z",
        unreadCount: 1,
        isOnline: false,
    },
    {
        id: "dm-demo-04",
        otherUserId: "demo-dating-10",
        otherUserName: "Mia Mitchell",
        otherUserAvatar: "https://i.pravatar.cc/200?img=44",
        isVerified: true,
        sharedEventTitle: "Rooftop Cinema Club",
        lastMessage: "Don't forget tomorrow starts at 9:00 sharp.",
        lastMessageTime: "2026-06-04T16:05:00.000Z",
        unreadCount: 0,
        isOnline: true,
    },
    {
        id: "dm-demo-05",
        otherUserId: "demo-dating-12",
        otherUserName: "Ivy Harris",
        otherUserAvatar: "https://i.pravatar.cc/200?img=45",
        isVerified: true,
        sharedEventTitle: "House of Afro",
        lastMessage: "This soundtrack is stuck in my head all day.",
        lastMessageTime: "2026-06-03T19:26:00.000Z",
        unreadCount: 0,
        isOnline: false,
    },
    {
        id: "dm-demo-06",
        otherUserId: "demo-dating-13",
        otherUserName: "Bella Nelson",
        otherUserAvatar: "https://i.pravatar.cc/200?img=48",
        isVerified: true,
        sharedEventTitle: "Sunset Sessions",
        lastMessage: "I bought tickets for Friday. Hope you're free!",
        lastMessageTime: "2026-06-02T14:12:00.000Z",
        unreadCount: 0,
        isOnline: false,
    },
];

// ── New Matches (no messages sent yet) ───────────────────────────────────────

export interface DemoNewMatch {
    id: string;
    userId: string;
    name: string;
    photoURL: string;
    isVerified: boolean;
    sharedEventTitle: string;
    matchedAt: string;
    isNew: boolean; // red dot
}

export const DEMO_NEW_MATCHES: DemoNewMatch[] = [
    {
        id: "newmatch-01",
        userId: "demo-dating-06",
        name: "Sofia",
        photoURL: "https://i.pravatar.cc/200?img=32",
        isVerified: true,
        sharedEventTitle: "Aqua Sundays",
        matchedAt: "2026-06-05T10:00:00.000Z",
        isNew: true,
    },
    {
        id: "newmatch-02",
        userId: "demo-dating-08",
        name: "Olivia",
        photoURL: "https://i.pravatar.cc/200?img=20",
        isVerified: false,
        sharedEventTitle: "Eclipse",
        matchedAt: "2026-06-05T08:30:00.000Z",
        isNew: true,
    },
    {
        id: "newmatch-03",
        userId: "demo-dating-02",
        name: "Ethan",
        photoURL: "https://i.pravatar.cc/200?img=5",
        isVerified: true,
        sharedEventTitle: "Eclipse",
        matchedAt: "2026-06-04T22:00:00.000Z",
        isNew: true,
    },
    {
        id: "newmatch-04",
        userId: "demo-dating-09",
        name: "Emma",
        photoURL: "https://i.pravatar.cc/200?img=57",
        isVerified: true,
        sharedEventTitle: "Afterhours",
        matchedAt: "2026-06-04T19:00:00.000Z",
        isNew: false,
    },
    {
        id: "newmatch-05",
        userId: "demo-dating-12",
        name: "Noah",
        photoURL: "https://i.pravatar.cc/200?img=36",
        isVerified: true,
        sharedEventTitle: "House of Afro",
        matchedAt: "2026-06-03T21:00:00.000Z",
        isNew: false,
    },
    {
        id: "newmatch-06",
        userId: "demo-dating-13",
        name: "Amelia",
        photoURL: "https://i.pravatar.cc/200?img=70",
        isVerified: true,
        sharedEventTitle: "No Signal",
        matchedAt: "2026-06-03T14:00:00.000Z",
        isNew: false,
    },
];

// ── DM Messages (keyed by conversation id) ───────────────────────────────────

export const DEMO_DM_MESSAGES: Record<string, { id: string; senderId: string; content: string; type: "text" | "image"; createdAt: string }[]> = {
    "dm-demo-01": [
        { id: "dm-01-001", senderId: "demo-user-001", content: "100%! I actually added one of the tracks to my playlist right after the movie.", type: "text", createdAt: "2026-06-05T22:12:00.000Z" },
        { id: "dm-01-002", senderId: "demo-dating-01", content: "Same here.", type: "text", createdAt: "2026-06-05T22:13:00.000Z" },
        { id: "dm-01-003", senderId: "demo-dating-01", content: "Been listening to it all morning.", type: "text", createdAt: "2026-06-05T22:13:30.000Z" },
        { id: "dm-01-004", senderId: "demo-user-001", content: "You know what?", type: "text", createdAt: "2026-06-05T22:23:00.000Z" },
        { id: "dm-01-005", senderId: "demo-user-001", content: "If they ever make a sequel, we're going together. No excuses.", type: "text", createdAt: "2026-06-05T22:24:00.000Z" },
        { id: "dm-01-006", senderId: "demo-dating-01", content: "Deal!", type: "text", createdAt: "2026-06-05T22:26:00.000Z" },
        { id: "dm-01-007", senderId: "demo-dating-01", content: "And popcorn's on you.", type: "text", createdAt: "2026-06-05T22:26:30.000Z" },
        { id: "dm-01-008", senderId: "demo-user-001", content: "Haha, fine... as long as you bring the drinks!", type: "text", createdAt: "2026-06-05T22:28:00.000Z" },
        { id: "dm-01-009", senderId: "demo-dating-01", content: "Done.", type: "text", createdAt: "2026-06-05T22:31:00.000Z" },
    ],
    "dm-demo-02": [
        { id: "dm-02-001", senderId: "demo-user-001", content: "That ending caught me completely off guard.", type: "text", createdAt: "2026-06-05T12:48:00.000Z" },
        { id: "dm-02-002", senderId: "demo-dating-04", content: "I can't believe that ending, totally unexpected!", type: "text", createdAt: "2026-06-05T12:54:00.000Z" },
    ],
    "dm-demo-03": [
        { id: "dm-03-001", senderId: "demo-user-001", content: "I finally started the series you recommended.", type: "text", createdAt: "2026-06-04T20:50:00.000Z" },
        { id: "dm-03-002", senderId: "demo-dating-07", content: "Hey, did you finish the series I recommended?", type: "text", createdAt: "2026-06-04T21:18:00.000Z" },
    ],
    "dm-demo-04": [
        { id: "dm-04-001", senderId: "demo-user-001", content: "I'll be there a little early.", type: "text", createdAt: "2026-06-04T15:45:00.000Z" },
        { id: "dm-04-002", senderId: "demo-dating-10", content: "Don't forget tomorrow starts at 9:00 sharp.", type: "text", createdAt: "2026-06-04T16:05:00.000Z" },
    ],
    "dm-demo-05": [
        { id: "dm-05-001", senderId: "demo-dating-12", content: "This soundtrack is stuck in my head all day.", type: "text", createdAt: "2026-06-03T19:26:00.000Z" },
    ],
    "dm-demo-06": [
        { id: "dm-06-001", senderId: "demo-dating-13", content: "I bought tickets for Friday. Hope you're free!", type: "text", createdAt: "2026-06-02T14:12:00.000Z" },
    ],
};

// ── Group Chat Messages (keyed by eventId) ────────────────────────────────────

export const DEMO_CHAT_MESSAGES: Record<string, import("@/lib/social/types").GroupMessage[]> = {
    "demo-event-01": [
        {
            id: "msg-01-001",
            eventId: "demo-event-01",
            senderId: "demo-host-01",
            senderName: "Colosseum Pune",
            senderAvatar: DEMO_POSTERS.logoCircle,
            senderBadge: "venue",
            content: "🔥 Gates open at 9 PM sharp! Please carry a valid ID. Stage 1 starts at 10 PM.",
            type: "announcement",
            createdAt: "2026-04-26T09:00:00.000Z",
        },
        {
            id: "msg-01-002",
            eventId: "demo-event-01",
            senderId: "demo-dating-01",
            senderName: "Ananya K.",
            senderAvatar: "https://i.pravatar.cc/100?img=47",
            content: "SO excited for tonight! First time at Colosseum 😍",
            type: "text",
            createdAt: "2026-04-26T10:15:00.000Z",
        },
        {
            id: "msg-01-003",
            eventId: "demo-event-01",
            senderId: "demo-dating-06",
            senderName: "Meera J.",
            senderAvatar: "https://i.pravatar.cc/100?img=32",
            content: "Anyone want to carpool from Koregaon Park? Have 2 spots 🚗",
            type: "text",
            createdAt: "2026-04-26T11:30:00.000Z",
        },
        {
            id: "msg-01-004",
            eventId: "demo-event-01",
            senderId: "demo-dating-11",
            senderName: "Ishaan P.",
            senderAvatar: "https://i.pravatar.cc/100?img=61",
            content: "What's the dress code?",
            type: "text",
            createdAt: "2026-04-26T12:00:00.000Z",
        },
        {
            id: "msg-01-005",
            eventId: "demo-event-01",
            senderId: "demo-host-01",
            senderName: "Colosseum Pune",
            senderAvatar: DEMO_POSTERS.logoCircle,
            senderBadge: "venue",
            content: "Smart casual / party wear. No shorts or chappals please!",
            type: "announcement",
            createdAt: "2026-04-26T12:10:00.000Z",
        },
        {
            id: "msg-01-006",
            eventId: "demo-event-01",
            senderId: "demo-user-001",
            senderName: "Arjun M.",
            senderAvatar: "https://i.pravatar.cc/100?img=68",
            content: "Anyone know what time the second DJ set starts?",
            type: "text",
            createdAt: "2026-04-26T14:20:00.000Z",
        },
        {
            id: "msg-01-007",
            eventId: "demo-event-01",
            senderId: "demo-dating-01",
            senderName: "Ananya K.",
            senderAvatar: "https://i.pravatar.cc/100?img=47",
            content: "I heard it's 12:30 AM! Can't wait 🙌",
            type: "text",
            createdAt: "2026-04-26T14:35:00.000Z",
        },
    ],
    "demo-event-05": [
        {
            id: "msg-05-001",
            eventId: "demo-event-05",
            senderId: "demo-host-05",
            senderName: "Shiva Valley Goa",
            senderAvatar: DEMO_POSTERS.logoCircle,
            senderBadge: "venue",
            content: "🌊 Aloha fam! Gates open at 8 PM. International artist announcement dropping tonight. Stay tuned 🔊",
            type: "announcement",
            createdAt: "2026-05-09T10:00:00.000Z",
        },
        {
            id: "msg-05-002",
            eventId: "demo-event-05",
            senderId: "demo-dating-02",
            senderName: "Priya S.",
            senderAvatar: "https://i.pravatar.cc/100?img=5",
            content: "Living for this event omg 🌺🌺",
            type: "text",
            createdAt: "2026-05-09T11:00:00.000Z",
        },
        {
            id: "msg-05-003",
            eventId: "demo-event-05",
            senderId: "demo-dating-08",
            senderName: "Nisha P.",
            senderAvatar: "https://i.pravatar.cc/100?img=20",
            content: "🌴 Can't wait! Anyone else driving from Pune?",
            type: "text",
            createdAt: "2026-05-09T13:05:00.000Z",
        },
        {
            id: "msg-05-004",
            eventId: "demo-event-05",
            senderId: "demo-dating-13",
            senderName: "Vikram R.",
            senderAvatar: "https://i.pravatar.cc/100?img=70",
            content: "Goa local here 🙋 If anyone needs tips on the best food spots nearby, just ask!",
            type: "text",
            createdAt: "2026-05-09T15:00:00.000Z",
        },
        {
            id: "msg-05-005",
            eventId: "demo-event-05",
            senderId: "demo-user-001",
            senderName: "Arjun M.",
            senderAvatar: "https://i.pravatar.cc/100?img=68",
            content: "Vikram that would be amazing! We land at Dabolim at 6. What do you recommend?",
            type: "text",
            createdAt: "2026-05-09T15:20:00.000Z",
        },
        {
            id: "msg-05-006",
            eventId: "demo-event-05",
            senderId: "demo-dating-13",
            senderName: "Vikram R.",
            senderAvatar: "https://i.pravatar.cc/100?img=70",
            content: "Hit Fisherman's Wharf for seafood then Curlies for pre-party vibes. You're welcome 🦞",
            type: "text",
            createdAt: "2026-05-09T15:35:00.000Z",
        },
    ],
    "demo-event-03": [
        {
            id: "msg-03-001",
            eventId: "demo-event-03",
            senderId: "demo-host-03",
            senderName: "Bass Station India",
            senderAvatar: DEMO_POSTERS.logoCircle,
            senderBadge: "host",
            content: "📣 LINEUP REVEALED: Stage 1 — Stray + Ternion Sound. Stage 2 — Djinn & Juno. It's going to be special 💥",
            type: "announcement",
            createdAt: "2026-05-02T12:00:00.000Z",
        },
        {
            id: "msg-03-002",
            eventId: "demo-event-03",
            senderId: "demo-dating-07",
            senderName: "Rohan V.",
            senderAvatar: "https://i.pravatar.cc/100?img=15",
            content: "TERNION SOUND OMG I'VE BEEN WAITING FOR THIS",
            type: "text",
            createdAt: "2026-05-02T12:15:00.000Z",
        },
        {
            id: "msg-03-003",
            eventId: "demo-event-03",
            senderId: "demo-dating-04",
            senderName: "Siddharth N.",
            senderAvatar: "https://i.pravatar.cc/100?img=12",
            content: "🔥 NSCI Dome is going to go OFF this time",
            type: "text",
            createdAt: "2026-05-02T13:00:00.000Z",
        },
        {
            id: "msg-03-004",
            eventId: "demo-event-03",
            senderId: "demo-user-001",
            senderName: "Arjun M.",
            senderAvatar: "https://i.pravatar.cc/100?img=68",
            content: "Already there from 10 PM! Meet at the Stage 2 entrance?",
            type: "text",
            createdAt: "2026-05-03T21:00:00.000Z",
        },
        {
            id: "msg-03-005",
            eventId: "demo-event-03",
            senderId: "demo-dating-07",
            senderName: "Rohan V.",
            senderAvatar: "https://i.pravatar.cc/100?img=15",
            content: "Yes let's! Bringing my camera — proper photos incoming 📸",
            type: "text",
            createdAt: "2026-05-03T21:10:00.000Z",
        },
    ],
};
