export function toIso(value: any): any;
export function slugify(value: any): string;
export function normalizeFilterKey(value: any): string;
export function normalizeCityKey(value: any): string | null;
export function normalizeBoolean(value: any): boolean;
export function normalizeGuestDiscoverySort(value: any): "startAt" | "heatScore" | "publishedAt" | "priceMin";
export function normalizeDiscoverySort(value: any): "followersCount" | "nextEventAt" | "updatedAt";
export function normalizeGuestDiscoveryLimit(value: any, fallback?: number, max?: number): number;
export function isPublicProfileEnabled(entity?: {}): any;
export function toEventBoundaryTime(value: any, boundary?: string): number;
export function isCurrentOrUpcomingEvent(event?: {}): boolean;
export function normalizeStatusKey(event?: {}): "live" | "upcoming" | "canceled" | "ended";
export function isEventPublic(event?: {}): boolean;
export function isGuestDiscoveryVisible(event?: {}): boolean;
export function isEventDetailVisible(event?: {}): boolean;
export function computeHeatScore(event?: {}): number;
export function buildSearchText(parts?: any[]): string;
export function derivePriceRange(rawEvent?: {}, priceMin?: number, priceMax?: number): any;
export function deriveTickets(rawEvent?: {}, priceMin?: number): any;
export function extractStartTime(value: any): string;
export function paginateItems(items?: any[], limit?: number, cursor?: null): {
    items: any[];
    nextCursor: any;
    hasMore: boolean;
};
export function dedupeById(items?: any[]): any[];
export function pickAllowed(raw?: {}, keys?: any[]): {};
export function projectGuestEventCard(event?: {}): any;
export function buildEventCardReadModel(rawEvent?: {}, { readModelVersion }?: {
    readModelVersion?: number | undefined;
}): {
    eventId: any;
    id: any;
    slug: any;
    title: any;
    cityKey: string;
    cityLabel: any;
    areaKey: string;
    startAt: any;
    endAt: any;
    dayKey: any;
    lifecycle: any;
    visibility: string;
    posterUrl: any;
    image: any;
    hostId: any;
    hostName: any;
    hostSlug: any;
    venueId: any;
    venueName: any;
    venueSlug: any;
    venue: any;
    host: any;
    priceMin: number;
    priceMax: number;
    isFree: boolean;
    price: number;
    startingPrice: number;
    priceRange: any;
    tickets: any;
    availabilityLabel: any;
    tags: any;
    eventType: any;
    curatedCategory: any;
    category: any;
    heatScore: number;
    searchText: string;
    publishedAt: any;
    updatedAt: string;
    statusKey: string;
    description: any;
    summary: any;
    location: any;
    city: any;
    date: any;
    time: any;
    startDate: any;
    endDate: any;
    startDateTime: any;
    startTime: any;
    endTime: any;
    guests: any;
    trending: boolean;
    stats: any;
    readModelVersion: number;
    sourceUpdatedAt: any;
};
export function buildHostSummaryReadModel(host?: {}, eventCards?: any[], { readModelVersion }?: {
    readModelVersion?: number | undefined;
}): {
    hostId: any;
    id: any;
    slug: any;
    handle: any;
    name: any;
    displayName: any;
    avatar: any;
    photoURL: any;
    avatarUrl: any;
    cover: any;
    coverURL: any;
    coverUrl: any;
    role: any;
    city: any;
    neighborhood: any;
    location: any;
    cityKey: string;
    areaKey: string;
    vibes: any;
    genres: any;
    styleTags: any;
    verified: boolean;
    trending: boolean;
    popular: boolean;
    followers: number;
    followersCount: number;
    upcomingEventsCount: number;
    nextEventDate: any;
    nextEventAt: any;
    featuredEventIds: any[];
    bioShort: any;
    bio: any;
    searchText: string;
    updatedAt: string;
    readModelVersion: number;
    publicProfileEnabled: any;
    visibility: string;
};
export function buildVenueSummaryReadModel(venue?: {}, eventCards?: any[], { readModelVersion, menuAvailable, highlightsCount, }?: {
    readModelVersion?: number | undefined;
    menuAvailable?: boolean | undefined;
    highlightsCount?: number | undefined;
}): {
    venueId: any;
    id: any;
    slug: any;
    name: any;
    displayName: any;
    photoURL: any;
    logo: any;
    image: any;
    coverURL: any;
    coverImage: any;
    photoUrl: any;
    coverUrl: any;
    city: any;
    area: any;
    neighborhood: any;
    cityKey: string;
    areaKey: string;
    tags: any;
    genres: any;
    vibes: any;
    tablesAvailable: boolean;
    verified: boolean;
    isVerified: boolean;
    venueType: any;
    category: any;
    followers: number;
    followersCount: number;
    upcomingEventsCount: number;
    nextEventAt: any;
    menuAvailable: boolean;
    highlightsCount: number;
    bioShort: any;
    bio: any;
    description: any;
    searchText: string;
    updatedAt: string;
    readModelVersion: number;
    publicProfileEnabled: any;
    visibility: string;
};
export function projectHostDetail(rawHost?: {}, summary?: {}): {
    id: any;
    name: any;
    displayName: any;
    avatar: any;
    photoURL: any;
    coverURL: any;
    cover: any;
    bio: any;
    description: any;
    followers: number;
    followersCount: number;
};
export function projectVenueDetail(rawVenue?: {}, summary?: {}, menuDoc?: null): {
    id: any;
    name: any;
    photoURL: any;
    image: any;
    coverURL: any;
    coverImage: any;
    area: any;
    neighborhood: any;
    followers: number;
    followersCount: number;
    verified: boolean;
    isVerified: boolean;
    menu: any;
    menuDoc: null;
};
export function buildGuestDiscoveryEnvelope(items?: any[], { nextCursor, hasMore, appliedFilters }?: {
    nextCursor?: null | undefined;
    hasMore?: boolean | undefined;
    appliedFilters?: {} | undefined;
}): {
    items: any[];
    nextCursor: null;
    hasMore: boolean;
    appliedFilters: {};
};
export function filterGuestEventCards(rawItems?: any[], query?: {}): {
    items: any[];
    nextCursor: null;
    hasMore: boolean;
    appliedFilters: {};
};
export function filterGuestHostSummaries(rawItems?: any[], query?: {}): {
    items: any[];
    nextCursor: null;
    hasMore: boolean;
    appliedFilters: {};
};
export function filterGuestVenueSummaries(rawItems?: any[], query?: {}): {
    items: any[];
    nextCursor: null;
    hasMore: boolean;
    appliedFilters: {};
};
export function rankGuestSearchGroups({ events, hosts, venues }?: {
    events?: any[] | undefined;
    hosts?: any[] | undefined;
    venues?: any[] | undefined;
}, query?: string, limit?: number): {
    events: any;
    hosts: any;
    venues: any;
};
export function normalizeEventSort(value: any): "startAt" | "heatScore" | "publishedAt" | "priceMin";
export function isGuestPublicProfileEnabled(entity?: {}): any;
export function isCurrentOrUpcomingGuestEvent(event?: {}): boolean;
export function isGuestEventPublic(event?: {}): boolean;
export function isGuestEventDetailVisible(event?: {}): boolean;
