name: Lighthouse CI

on:
  pull_request:
    branches: [main]
    paths:
      - apps/guest-portal/**
      - apps/admin-console/**
      - packages/ui/**

jobs:
  lhci:
    name: Lighthouse audit
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app: [guest-portal, admin-console]
    env:
      DEV_TOY_MODE: "true"
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5
      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e
        with: { node-version: 20, cache: npm }
      - run: npm install --legacy-peer-deps
      - name: Build app
        run: npx turbo build --filter=@c1rcle/${{ matrix.app }}
        env:
          TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
          TURBO_TEAM: ${{ vars.TURBO_TEAM }}
      - name: Run Lighthouse CI
        run: npx @lhci/cli autorun --config=apps/${{ matrix.app }}/.lighthouserc.json --verbose
        continue-on-error: true
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
